### ISSUE TITLE
DHCP and Hiera support

### ISSUE THREAD

**Issue by weijianwen** [treydock/puppet-infiniband#5]
Hi,

I am new to Puppet and plan to migrate all my Ethernet and Mellanox Infiniband settings to Puppet. Hopefully, I plan to set Infiniband cards to request IP addresses via DHCP and manage all the settings in Hiera. May I contribute to `puppet-infiniband` to fulfill the tasks above? Where shall I start in the source tree?

Thank you.

**Comment by anadon** [comment]
Usually you just make the pull request.

**Comment by treydock** [comment]
@weijianwen Open a pull request with your proposed changes.
