### ISSUE TITLE
Changed package names in EL-7.4

### ISSUE THREAD

**Issue by mrolli** [treydock/puppet-infiniband#9]
Just to inform you... the IB packages list changed from EL 7.3->7.4.

We need another case handling... yeah...

As this hits me hard, I'll have to fix this rather soon.

**Comment by mrolli** [comment]
This is the new group list in 7.4. I'll try to simply extend the conditional block in params.pp. Watch out, pull request ahead...

`Group: Infiniband Support
 Group-Id: infiniband
 Description: Software designed for supporting clustering and grid connectivity using RDMA-based InfiniBand and iWARP fabrics.
 Mandatory Packages:
    libibcm
    libibverbs
    libibverbs-utils
    librdmacm
    librdmacm-utils
 Default Packages:
    dapl
    ibacm
    ibutils
    infiniband-diags
   +iwpmd
   +libcxgb3
   +libcxgb4
   +libhfi1
   +libi40iw
    libibmad
    libibumad
   +libipathverbs
   +libmlx4
   +libmlx5
   +libmthca
   +libnes
   +libocrdma
    mstflint
   +opa-address-resolution
   +opa-fastfabric
    perftest
    qperf
   +rdma-ndd
    srp_daemon
 Optional Packages:
   compat-dapl
   compat-opensm-libs
   libibcommon
   libusnic_verbs
   libvma
   opensm
   rdma-core
   usnic-tools
 Conditional Packages:
   +glusterfs-rdma`

**Comment by mrolli** [comment]
@treydock Does the distribution of packages to base/optional in params.pp reflect the distribution in the group file of group infiniband until now? I can live with that, but as you see above, many tools that were optional are now in default (mstflint, perftest, qperf, ...) though one does not install them everywhere.
I won't take opensm into the list as you also ommited this one, but I'd like to bring a separate PR to manage OpenSM using your module at some point in the future.

**Comment by treydock** [comment]
@mrolli I have an opensm module here: https://github.com/treydock/puppet-module-opensm

**Comment by mrolli** [comment]
Oh, actually I didn't even search for that because I naturally felt that this should be a feature of the infiniband module itself as the two are naturally dependent. An infiniband network needs a subnet manger and vice-versa.
